name: 'Yandex Serverless Action'
description: 'Deploy new version of Serverless function to Yandex Cloud'
author: 'Goodsmileduck'
branding:
  color: 'blue'
  icon: 'upload-cloud'
inputs:
  function_id:
    description: 'Function name in Yandex Cloud'
    default: ''
    required: true
  runtime:
    description: 'Runtime for function'
    default: ''
    required: true
  entrypoint:
    description: 'Entrypoint for function'
    default: ''
    required: true
  source:
    description: 'Source directory for cloud function in git repo'
    default: '.'
    required: false
  memory:
    description: 'Memory in Mb'
    default: '256'
    required: false
  environment:
    description: 'Env variables for function'
    default: ''
    required: false
  token:
    description: 'Oauth token'
    default: ''
    required: false
  execution_timeout:
    description: 'Execution timeout'
    default: ''
    required: false
  exclude:
    description: 'exclude pattern for source directory'
    default: ''
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'