name: Build docker image

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Push docker image
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v1
      - uses: docker/build-push-action@v1
        with:
          push: False