  
name: Javascript action

on: [push]

jobs:
  deploy_one_by_one:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Deploy from Folder
      uses: goodsmileduck/yandex-serverless-action@javascript
      with:
        source: 'example'
        exclude: 'exclude.txt'
        function_id: 'd4ecd1ho7t9ieugt9q58'
        folder_id: ${{ secrets.FOLDER_ID }}
        runtime: 'python37'
        entrypoint: handler.hello
        environment: SOME=User Name <info@domain.com>,BOSS=1,NEW=true
        token: ${{ secrets.TOKEN }}
        execution_timeout: '600'
    - name: Deploy from Bucket
      uses: goodsmileduck/yandex-serverless-action@javascript
      with:
        source: 'example'
        function_id: 'd4e9st6hefepjghdv67s'
        folder_id: ${{ secrets.FOLDER_ID }}
        runtime: 'python37'
        entrypoint: handler.hello
        environment: SOME=User Name <info@domain.com>,BOSS=1,NEW=true
        token: ${{ secrets.TOKEN }}
        execution_timeout: '600'
        bucket: 'yandex-functions'