  
name: Javascript action

on: [push]

jobs:
  deploy_from_folder:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: goodsmileduck/yandex-serverless-action@javascript
      with:
        source: 'example'
        function_id: 'd4ecd1ho7t9ieugt9q58'
        runtime: 'python37'
        entrypoint: handler.hello
        environment: SOME=User Name <info@domain.com>,BOSS=1,NEW=true
        token: ${{ secrets.TOKEN }}
        execution_timeout: '600'

  deploy_from_bucket:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: goodsmileduck/yandex-serverless-action@javascript
      with:
        source: 'example'
        function_id: 'hello-bucket'
        runtime: 'python37'
        entrypoint: handler.hello
        environment: SOME=User Name <info@domain.com>,BOSS=1,NEW=true
        token: ${{ secrets.TOKEN }}
        execution_timeout: '600'
        bucket: 'yandex-functions'
        access_key: ${{ secrets.ACCESS_KEY }}
        secret_key: ${{ secrets.SECRET_KEY }}